[build]
  publish = "."
  command = "npm install"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[dev]
  command = "npm run dev"
  port = 8000
  publish = "."

[[plugins]]
  package = "@netlify/plugin-functions-install-core"